name: template #CHANGE for your project
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pyyaml # import python packages by naming them as dependencies and potentially specifying version numbers
  - numpy
  - matplotlib
  - gitpython
  - termcolor
  - colorama
  - jupyter
  - linearmodels
  # - pip=19
  # - pip: # if there is a package available via pip but not with conda, can import like this:
  #     - EXAMPLE_PACKAGE
  - r=4.2
  - r-data.table
  - r-ggplot2
  - r-Rcpp
  - r-fst
  - r-fixest
  - r-zoo
  - r-stringr

